# Generated by Django 3.2.3 on 2021-05-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_auto_20210525_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_specie',
            name='pokemon_type',
            field=models.ManyToManyField(blank=True, to='identity.Pokemon_type'),
        ),
    ]
